(function(){var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){if(b==Array.prototype||b==Object.prototype)return b;b[a]=c.value;return b};
$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var a=0;a<b.length;++a){var c=b[a];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,a,c){if(!c||null!=b){c=$jscomp.propertyToPolyfillSymbol[a];if(null==c)return b[a];c=b[c];return void 0!==c?c:b[a]}};$jscomp.polyfill=function(b,a,c,d){a&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,a,c,d):$jscomp.polyfillUnisolated(b,a,c,d))};
$jscomp.polyfillUnisolated=function(b,a,c,d){c=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var f=b[d];if(!(f in c))return;c=c[f]}b=b[b.length-1];d=c[b];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})};
$jscomp.polyfillIsolated=function(b,a,c,d){var f=b.split(".");b=1===f.length;d=f[0];d=!b&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var m=0;m<f.length-1;m++){var n=f[m];if(!(n in d))return;d=d[n]}f=f[f.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[f]:null;a=a(c);null!=a&&(b?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:a}):a!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[f]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+c+"$"+f),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[f],{configurable:!0,writable:!0,value:a})))};
$jscomp.polyfill("String.prototype.replaceAll",function(b){return b?b:function(a,c){if(a instanceof RegExp&&!a.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return a instanceof RegExp?this.replace(a,c):this.replace(new RegExp(String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}},"es_2021","es3");
$jscomp.checkStringArgs=function(b,a,c){if(null==b)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return b+""};
(function(){function b(e){clearTimeout(d);var h=(new Date).getTime()-c,k=e[1],p=e[2],g=e[3];h=e[0]-h;if("done"==g&&0<h)d=setTimeout(function(){b(e)},h);else{a.className="";var l=a.style;l.transitionDuration=l.TransitionDuration=k+"ms";l.width=p;"done"==g?(a.className=g,d=setTimeout(function(){l.width="0%"},k)):d=setTimeout(function(){a.className=g},k)}}window.sp=window.sp||{};window._ugi=function(e){for(var h=document.getElementById("guide"),k=0,p=h.children.length;k<p;k++){var g=h.children[k];try{g.hasAttribute("class")?
"guide-item-selected"==g.getAttribute("class")?g.removeAttribute("class"):g.setAttribute("class",g.getAttribute("class").replaceAll(" guide-item-selected","")):reportError("Cannot remove a class from an element lacking one!")}catch(l){reportError("Failed to remove class guide-item-selected")}}if(document.getElementById("guide-item-"+e)){e=document.getElementById("guide-item-"+e);try{e.hasAttribute("class")?e.setAttribute("class",e.getAttribute("class")+" guide-item-selected"):e.setAttribute("class",
"guide-item-selected")}catch(l){reportError("Failed to add class guide-item-selected")}}};var a=null,c=-1,d=-1,f=[0,300,"95%","waiting"],m=[100,25,"101%","waiting"],n=[125,150,"101%","done"];document.addEventListener("spfclick",function(e){a=document.createElement("div");a.setAttribute("id","progress");a.innerHTML="<dt></dt><dd></dd>";document.body.appendChild(a)});document.addEventListener("spfrequest",function(e){c=(new Date).getTime();b(f)});document.addEventListener("spfprocess",function(e){b(m)});
document.addEventListener("spfdone",function(e){b(n);clearTimeout(d);a.className="";e=a.style;e.transitionDuration=e.TransitionDuration="0ms";e.width="0%";a=null;document.getElementById("progress").remove()})})();})();
